name: bwmuaphotography
favicon: null
layout_spectrum: 0.7432585118804127
typography_spectrum: 0.15149157214909792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5558057050220668
  lightness: 0.14077213150449097
  saturation: 0.09770851186476648
  rhythmicContrast: 0.6062687439844012
purpose: []
